// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLife Pro - Transforme seu corpo com treinos personalizados",
  description: "Planos de treino e dieta personalizados com IA, cronômetros inteligentes e acompanhamento completo. Teste grátis por 7 dias.",
  keywords: [
    "FitLife Pro",
    "treino personalizado",
    "dieta personalizada",
    "fitness app",
    "emagrecimento",
    "ganho de massa muscular",
    "HIIT",
    "cronômetro treino",
    "app fitness",
    "academia",
    "saúde",
    "bem-estar",
    "transformação corporal",
    "perder peso",
    "definição muscular"
  ],
  authors: [{ name: "FitLife Pro Team" }],
  creator: "FitLife Pro",
  publisher: "FitLife Pro",
  applicationName: "FitLife Pro",
  category: "Health & Fitness",
  
  // Open Graph (Facebook, LinkedIn, WhatsApp)
  openGraph: {
    type: "website",
    locale: "pt_BR",
    url: "https://fitlifepro.app",
    siteName: "FitLife Pro",
    title: "FitLife Pro - Transforme seu corpo com treinos personalizados",
    description: "Planos de treino e dieta personalizados com IA, cronômetros inteligentes e acompanhamento completo. Teste grátis por 7 dias.",
    images: [
      {
        url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=630&fit=crop",
        width: 1200,
        height: 630,
        alt: "FitLife Pro - App de Fitness",
      },
    ],
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "FitLife Pro - Transforme seu corpo com treinos personalizados",
    description: "Planos de treino e dieta personalizados com IA, cronômetros inteligentes e acompanhamento completo. Teste grátis por 7 dias.",
    images: ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=630&fit=crop"],
    creator: "@fitlifepro",
  },

  // PWA & Mobile
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "FitLife Pro",
  },
  
  // Verificação e indexação
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  // Outros metadados importantes
  alternates: {
    canonical: "https://fitlifepro.app",
  },
  
  // Informações de contato e verificação
  verification: {
    // Adicione aqui seus códigos de verificação quando tiver:
    // google: "seu-codigo-google-search-console",
    // yandex: "seu-codigo-yandex",
    // bing: "seu-codigo-bing",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        
        {/* Metadados adicionais para SEO */}
        <meta name="theme-color" content="#9333ea" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        
        {/* Preconnect para performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* Schema.org para Google */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "MobileApplication",
              "name": "FitLife Pro",
              "applicationCategory": "HealthApplication",
              "operatingSystem": "iOS, Android, Web",
              "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "BRL",
                "description": "7 dias grátis, depois R$ 29,90/mês"
              },
              "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": "4.9",
                "ratingCount": "2500",
                "bestRating": "5",
                "worstRating": "1"
              },
              "description": "Planos de treino e dieta personalizados com IA, cronômetros inteligentes e acompanhamento completo.",
              "screenshot": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=630&fit=crop"
            })
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
